company_account/urls.py
from django.conf.urls import patterns, url
from company_account import views
# from workspace import views as wp_views


urlpatterns = patterns('',

   url(r'^registration/$',views.partner_register,  name='registration'),
    url(r'^login/$',   views.user_login,  name='user_login'),
    url(r'^profile/update/$',   views.profile_update,  name='profile_update'),
    # url(r'^profile/$',   views.profile_info,  name='profile_info'),
    url(r'^logout/$',   views.user_logout,  name='user_logout'),
    url(r'^password/change/$',   views.userPasswordChange,  name='password_change'),

    url(r'^edit/$',   views.companyChange,  name='edit_company'),

    url(r'^company-profile/edit/$',   views.companyProfileChange,  name='edit_profile'),
    url(r'^company-capacity/edit/$',   views.companyCapacityChange,  name='edit_capacity'),

    url(r'^company-clients/new/$',   views.add_client,  name='add_client'),
    url(r'^company-clients/(?P<id>.*?)/$',   views.companyClientChange,  name='edit_client'),

    url(r'^company-products/new/$',   views.add_product,  name='add_product'),
    url(r'^company-products/(?P<id>.*?)/$',   views.companyProductChange,  name='edit_product'),

    url(r'^company-projects/new/$',   views.add_project,  name='add_project'),
    url(r'^company-projects/(?P<id>.*?)/$',   views.companyProjectChange,  name='edit_project'),

    url(r'^company-partners/new/$',   views.add_partner,  name='add_partner'),
    url(r'^company-partners/(?P<id>.*?)/$',   views.companyPartnerChange,  name='edit_partner'),

    url(r'^company-employees/new/$',   views.add_employee,  name='add_employee'),
    url(r'^company-employees/(?P<id>.*?)/$',   views.companyEmplooyesChange,  name='edit_employee'),

    url(r'^company-partnerships/new/$',   views.add_partnership,  name='add_partnership'),
    url(r'^company-partnerships/(?P<id>.*?)/$',   views.companyPartnershipChange,  name='edit_partnership'),

    url(r'^company-certificates/new/$',   views.add_certificate,  name='add_certificate'),
    url(r'^company-certificates/(?P<id>.*?)/$',   views.companyCertificateChange,  name='edit_certificate'),

    url(r'^company-technologies/new/$',   views.add_technology,  name='add_technology'),
    url(r'^company-technologies/(?P<id>.*?)/$',   views.companyTechnologyChange,  name='edit_technology'),

    url(r'^$', views.company_page,  name='company_page'),






    url(r'^confirm/(?P<activation_key>[-\w]+)/$',   views.user_confirm,  name='user_confirm'),
    #user actions

)

core/urls.py
from django.conf.urls import patterns, url
from core import views
# from workspace import views as wp_views


urlpatterns = patterns('',

   # url(r'^registration/$',views.partner_register,  name='registration'),
   url(r'^(?P<slug>.*?)/$',views.CompanyView.as_view(),  name='company_view'),



    #user actions

)

eurocatalog/urls.py
from django.conf.urls import patterns, include, url

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from core.views import index,search,HomePageView,use_session
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



admin.autodiscover() 
urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # url(r'^', include('core.urls', namespace='core')),
    url(r'^$',HomePageView.as_view(),  name='index'),
   url(r'^session/$',use_session,  name='use_session'),



    url(r'^search/$', search,  name='search'),
    url(r'^categories/', include('catalog.urls', namespace='catalog')),
    url(r'^company/', include('core.urls', namespace='company')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^publications/', include('publications.urls', namespace='publications')),
    url(r'^enterpreneurship/', include('business_info.urls', namespace='enterpreneurship')),
    url(r'^sites/', include('sites.urls', namespace='sites')),
    url(r'^exhibitions/', include('exhibitions.urls', namespace='exhibitions')),
    url(r'^library/',include('library.urls',namespace='library')),
    url(r'^account/',include('company_account.urls',namespace='company_account')),
)

# ... the rest of your URLconf goes here ...

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from news import views





urlpatterns = patterns('',
    url(r'^$',
        views.news_list, name='news_archive_index'),

    url(r'^(?P<slug>[-\w]+)/$',
        views.news_detail, name='news_detail'),
)

company_account/models.py
from django.db import models

# Create your models here.

company_account/views.py
from django.views import generic as generic_views
# from django.views import FormMixin, ListView
# from . import models,settings
# from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.template import RequestContext
# Http
from django.http import HttpResponse, Http404,HttpResponseRedirect
#json
from django.core.serializers.json import DjangoJSONEncoder
import json
#mail
from django.core.mail import send_mail
#settings
from eurocatalog.settings import EMAIL_HOST_USER, PORTAL_URL
# models
#form
from company_account.forms import RegisterForm,LoginForm,PasswordChangeForm,CustomUserCreationForm,UpdatePartnerForm,\
                                UpdateUserForm
from django.shortcuts import render,render_to_response,get_object_or_404,redirect
# Create your views here.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~BOOK CATEGORY LIST~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
from django.http import HttpResponseRedirect,Http404
# from .forms import UploadFileForm
from django.utils import translation
from django.utils import timezone
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.core.context_processors import csrf
from django.core.mail import send_mail, BadHeaderError
from django.db.models import Q
# Create your views here.
# from core.models import User
from django.views.generic.edit import FormMixin
from django.views.generic.list import ListView

from news.models import News
from publications.models import Publications
from sites.models import Sites
from exhibitions.models import Exhibitions
from core.models import Company,CompanyProfile,CompanyProducts,CompanyProjects,CompanyPartnership,CompanyCapacity,Categories,\
    CompanyPartners,CompanyClients,CompanyEmployees,UserProfile,UserPasswordRecovery,CustomUserManager,User,CompanyCertificates,CompanyTechnology
from business_info.models import Stage,BusinessInfo
#python
import datetime, random, sha
# Authentication
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
#Forms
from core.forms import CompanyPartnersForm,CompanyProjectsForm,CompanyProductsForm,CompanyClientsForm,CompanyEmployeesForm,\
    CompanyCertificatesForm,CompanyPartnershipForm,CompanyTechnologyForm,CompanyProfileForm,CompanyCapacityForm,CompanyForm


# Create your views here.
# class CompanyPageView(ListView):
#     model = Company
#     template_name = 'company_account/company_page.html'
#     user = request.user
#
#     @login_required()
#
#     def get_context_data(self, **kwargs):
#         context = super(CompanyPageView, self).get_context_data(**kwargs)
#         # user = self.request.user
#         # context['user'] = user
#
#         return context

@login_required()
def company_page(request):
    company = Company.objects.get(id=request.user.company_id)
    company_profile = CompanyProfile.objects.get(company=company.id)
    company_capacity = CompanyCapacity.objects.get(company=company.id)

    company_projects = CompanyProjects.objects.filter(company = company.id)
    company_products = CompanyProducts.objects.filter(company=company.id)
    company_partners = CompanyPartners.objects.filter(company=company.id)
    company_partnership = CompanyPartnership.objects.filter(company=company.id)
    company_employees = CompanyEmployees.objects.filter(company=company.id)
    company_clients = CompanyClients.objects.filter(company=company.id)
    company_certificates = CompanyCertificates.objects.filter(company=company.id)
    company_technology = CompanyTechnology.objects.filter(company=company.id)

    return render_to_response('company_account/company_page.html',
                              {'company':company,'company_projects':company_projects,
                               'company_products':company_products,'company_partners':company_partners,
                               'company_partnership':company_partnership,'company_employees':company_employees,
                              'company_clients':company_clients,'company_certificates':company_certificates,
                              'company_technology':company_technology,
                              'company_profile':company_profile,
                              'company_capacity':company_capacity
                              },
                              context_instance=RequestContext(request))

def add_partner(request):

    form = CompanyPartnersForm()

    if request.method == 'POST':
        form = CompanyPartnersForm(request.POST, request.FILES)

        if form.is_valid():
            partner = form.save(commit=False)
            partner.save()

        return redirect('/account')
    return render_to_response('company_account/add/add_partner.html',
                                  {'form': form},
                                  context_instance=RequestContext(request)
                              )

def add_project(request):

    form = CompanyProjectsForm()

    if request.method == 'POST':
        form = CompanyProjectsForm(request.POST, request.FILES)
        if form.is_valid():
            project = form.save(commit=False)
            project.save()

        return redirect('/account')
    return render_to_response('company_account/add/add_project.html',
                                  {'form': form},
                                  context_instance=RequestContext(request)
                              )

def add_product(request):

    form = CompanyProductsForm()

    if request.method == 'POST':
        form = CompanyProductsForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()

        return redirect('/account')
    return render_to_response('company_account/add/add_product.html',
                                  {'form': form},
                                  context_instance=RequestContext(request)
                              )

def add_client(request):

    form = CompanyClientsForm()

    if request.method == 'POST':
        form = CompanyClientsForm(request.POST, request.FILES)
        if form.is_valid():
            client = form.save(commit=False)
            client.save()

        return redirect('/account')
    return render_to_response('company_account/add/add_client.html',
                                  {'form': form},
                                  context_instance=RequestContext(request)
                              )


def add_employee(request):

    form = CompanyEmployeesForm()
    if request.method == 'POST':
        form = CompanyEmployeesForm(request.POST, request.FILES)
        # when form is valid register user
        if form.is_valid():
            employee = form.save(commit=False)
            employee.save()

        return redirect('/account')
    return render_to_response('company_account/add/add_employee.html',
                                  {'form': form},
                                  context_instance=RequestContext(request)
                              )

def add_partnership(request):

    form = CompanyPartnershipForm()

    if request.method == 'POST':
        form = CompanyPartnershipForm(request.POST, request.FILES)
        # when form is valid register user
        if form.is_valid():
            partnership = form.save(commit=False)
            partnership.save()
        return redirect('/account')
    return render_to_response('company_account/add/add_partnership.html',
                                  {'form': form},
                                  context_instance=RequestContext(request)
                              )


def add_certificate(request):
    form = CompanyCertificatesForm()

    if request.method == 'POST':
        form = CompanyCertificatesForm(request.POST, request.FILES)
        # when form is valid register user
        if form.is_valid():
            certificate = form.save(commit=False)
            certificate.save()

        return redirect('/account')
    return render_to_response('company_account/add/add_certificate.html',
                                  {'form': form},
                                  context_instance=RequestContext(request)
                              )

def add_technology(request):

    form = CompanyTechnologyForm()

    if request.method == 'POST':
        form = CompanyTechnologyForm(request.POST)
        # when form is valid register user
        if form.is_valid():
            technology = form.save(commit=False)
            technology.save()

        return redirect('/account')
    return render_to_response('company_account/add/add_technology.html',
                                  {'form': form},
                                  context_instance=RequestContext(request)
                              )

@login_required
def companyPartnerChange(request,id):
    partner = CompanyPartners.objects.get(pk=id)
    user = request.user

    partnerForm = CompanyPartnersForm(request.POST,request.FILES, instance=partner)

    if request.method == 'POST':
        if partnerForm.is_valid():
            update_partner = partnerForm.save(commit=False)
            update_partner.save()
            return redirect('/account')

    else:
        partnerForm = CompanyPartnersForm(instance=partner)

    return render_to_response('company_account/edit/edit_partner.html',
                                 {'partnerForm': partnerForm,'partnerid':id},
                                 context_instance=RequestContext(request)
                              )

@login_required
def companyProductChange(request,id):
    product = CompanyProducts.objects.get(pk=id)
    user = request.user

    productForm = CompanyProductsForm(request.POST,request.FILES, instance=product)

    if request.method == 'POST':
        if productForm.is_valid():
            update_product = productForm.save(commit=False)
            update_product.save()
            return redirect('/account')

    else:

templates/company_account/authorization.html
{% load i18n %}

 <div id="right-authorization">
            {% if user.is_authenticated %}

           <h3>{% trans 'Welcome' %} <br> {{ user.company.name }}</h3>
{#                <a class="ui green icon button" href="{% url 'company_account:user_logout' %}">{% trans 'Log out' %}</a>#}
                <a class="large ui orange button center" href="{% url 'company_account:company_page' %}">{% trans 'Account' %}</a><br><br>
                <a class="large ui orange button center" href="{% url 'company_account:user_logout' %}">{% trans 'Log out' %}</a>

  {% endif %}
    </div>

templates/company_account/company_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ company.name }}{% endblock %}

{% block content %}

    <div id="account-company">
    <h1>{{ company.name }}</h1> <a  class="mini ui blue button right" href="{% url 'company_account:edit_company' %}">{% trans 'Edit' %}</a>
      <div class="main-detail">
         <div class="image">
            <img src="{{ MEDIA_URL }}{{ company.logo }}">
        </div>
        <ul>

            <li class="comp_type">{% for type in company.comp_type.all  %}{{ type.name }} ; {% endfor %}</li>
            <li class="address">{{ company.address }}</li>
            <li class="phone">{{ company.phone }}</li>
            <li class="fax">{{ company.fax }}</li>
            <li class="site"><a href="{{ company.url }}" target="_blank">{{ company.url }}</a> </li>
        </ul>

    </div>
{#    {% for project in company_projects %}#}
{#        {{ project.name }}#}
{##}
{#    {% endfor %}#}

    <div class="company-section">
        <h2>{% trans 'Company Profile' %}</h2>
        <a  class="mini ui blue button right" href="{% url 'company_account:edit_profile' %}">{% trans 'Edit Profile' %}</a>
        <h4>{% trans 'Mission' %}</h4>{{ company_profile.mission|striptags|safe }}
        <h4>{% trans 'History' %}</h4>{{ company_profile.history|striptags|safe }}
    </div>

     <div class="company-section">
    <table class="ui table segment">
    <thead>
    <h2>{% trans 'Capacity' %}</h2><a class="mini ui blue button right" href="{% url 'company_account:edit_capacity' %}">{% trans 'Edit Capacity' %}</a>
            <tr>
                <th class="text-left">{% trans 'Manufempl' %}</th>
                <th class="text-left">{% trans 'Manageempl' %}</th>
                <th class="text-left">{% trans 'Volume' %}</th>
                <th class="text-left">{% trans 'Production Space' %}</th>
            </tr>
    </thead>

    <tbody>
        <tr>
            <td>{{ company_capacity.manufempl }}</td>
            <td>{{ company_capacity.manageempl }}</td>
            <td>{{ company_capacity.volume }}</td>
            <td>{{ company_capacity.production_space }}</td>
        </tr>
    </tbody>
</table>
    </div>

    <div class="company-section">
    <table class="ui table segment">
    <thead>
    <h2>{% trans 'Partners' %}</h2><a class="mini ui blue button right" href="{% url 'company_account:add_partner' %}">{% trans 'Add New Partner' %}</a>
            <tr>
                <th class="text-left">{% trans 'Partner' %}</th>
                <th class="text-left">{% trans 'Partner Type' %}</th>
                <th class="text-left">{% trans 'Since' %}</th>
            </tr>
    </thead>

    <tbody>
    {% for partner in company_partners %}
        <tr>
            <td><a href="{% url 'company_account:edit_partner' id=partner.id %}">{{ partner.partner }} </a> </td>
            <td>{{ partner.partnertype }}</td>
            <td>{{ partner.since }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
    </div>

    <div class="company-section">
    <table class="ui table segment">
    <thead>
    <h2>{% trans 'Clients' %}</h2><a class="mini ui blue button right" href="{% url 'company_account:add_client' %}">{% trans 'Add New Client' %}</a>
            <tr>
                <th class="text-left">{% trans 'Client' %}</th>
                <th class="text-left">{% trans 'Product Service' %}</th>
                <th class="text-left">{% trans 'Since' %}</th>
            </tr>
    </thead>

    <tbody>
    {% for client in company_clients %}
        <tr>
            <td><a href="{% url 'company_account:edit_client' id=client.id %}">{{ client.client }} </a> </td>
            <td>{{ client.product_service }}</td>
            <td>{{ client.since }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
    </div>

       <div class="company-section">
    <table class="ui table segment">
    <thead>
    <h2>{% trans 'Employees' %}</h2><a class="mini ui blue button right" href="{% url 'company_account:add_employee' %}">{% trans 'Add New Employee' %}</a>
            <tr>
                <th class="text-left">{% trans 'FullName' %}</th>
                <th class="text-left">{% trans 'Position' %}</th>
                <th class="text-left">{% trans 'About' %}</th>
            </tr>
    </thead>

    <tbody>
    {% for employee in company_employees %}
        <tr>
            <td><a href="{% url 'company_account:edit_employee' id=employee.id %}">{{ employee.fullname }} </a> </td>
            <td>{{ employee.position }}</td>
            <td>{{ employee.about|striptags|safe|truncatewords:20 }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
    </div>

    <div class="company-section">
    <table class="ui table segment">
    <thead>
    <h2>{% trans 'Products' %}</h2><a class="mini ui blue button right" href="{% url 'company_account:add_product' %}">{% trans 'Add New Product' %}</a>
            <tr>
                <th class="text-left">{% trans 'Name' %}</th>
                <th class="text-left">{% trans 'Link' %}</th>
            </tr>
    </thead>

    <tbody>
    {% for product in company_products %}
        <tr>
            <td><a href="{% url 'company_account:edit_product' id=product.id %}">{{ product.name }} </a> </td>
            <td><a target="_blank" href="{{ product.link }}">{% trans 'Go to Site' %}</a> </td>
        </tr>
    {% endfor %}
    </tbody>

</table>
    </div>

    <div class="company-section">
    <table class="ui table segment">
    <thead>
    <h2>{% trans 'Projects' %}</h2> <a class="mini ui blue button right" href="{% url 'company_account:add_project' %}">{% trans 'Add New Project' %}</a>
            <tr>
                <th class="text-left">{% trans 'Name' %}</th>
                <th class="text-left">{% trans 'Client' %}</th>
                <th class="text-left">{% trans 'Project type' %}</th>
                <th class="text-left">{% trans 'Role' %}</th>
                <th class="text-left">{% trans 'Begin date' %}</th>
                <th class="text-left">{% trans 'End Date' %}</th>
            </tr>
    </thead>

    <tbody>
    {% for project in company_projects %}
        <tr>
            <td><a href="{% url 'company_account:edit_project' id=project.id %}">{{ project.name }} </a> </td>
            <td>{{ project.client }}</td>
            <td>{{ project.project_type }}</td>
            <td>{{ project.role }} </td>
            <td>{{ project.begin_date }} </td>
            <td>{{ project.end_date }} </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
    </div>


    <div class="company-section">
    <table class="ui table segment">
    <thead>
        <h2>{% trans 'Partnerships' %}</h2> <a class="mini ui blue button right" href="{% url 'company_account:add_partnership' %}">{% trans 'Add New Partnership' %}</a>

            <tr>
                <th class="text-left">Name</th>
                <th class="text-left">File</th>
                <th class="text-left">Link</th>
            </tr>
    </thead>

    <tbody>
    {% for partnership in company_partnership %}
        <tr>
            <td><a href="{% url 'company_account:edit_partnership' id=partnership.id %}">{{ partnership.name }} </a> </td>
            <td><a target="_blank" href=" {{ partnership.file_name}}">{% trans 'Download File' %}</a></td>
            <td>{{ partnership.link }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
    </div>

{#              Technology            #}
      <div class="company-section">
    <table class="ui table segment">
    <thead>
        <h2>{% trans 'Certificates' %}</h2> <a class="mini ui blue button right" href="{% url 'company_account:add_certificate' %}">{% trans 'Add New Certificate' %}</a>

            <tr>
                <th class="text-left">{% trans 'Name' %}</th>
                <th class="text-left">{% trans 'Certification Company' %}</th>
                <th class="text-left">{% trans 'Receive year' %}</th>
                <th class="text-left">{% trans 'Download File' %}</th>
            </tr>
    </thead>

    <tbody>
    {% for certificate in company_certificates %}
        <tr>
            <td><a href="{% url 'company_account:edit_certificate' id=certificate.id %}">{{ certificate.name }} </a> </td>
            <td>{{ certificate.certification_company }}</td>
            <td>{{ certificate.receive_year }}</td>
            <td><a target="_blank" href=" {{ certificate.filename}}">{% trans 'Download File' %}</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
    </div>


      <div class="company-section">
    <table class="ui table segment">
    <thead>
        <h2>{% trans 'Technologies' %}</h2> <a class="mini ui blue button right" href="{% url 'company_account:add_partnership' %}">{% trans 'Add New Technology' %}</a>

            <tr>
                <th class="text-left">{% trans 'Equipment' %}</th>
                <th class="text-left">{% trans 'IT' %}</th>
                <th class="text-left">{% trans 'Resanddev' %}</th>
            </tr>
    </thead>

    <tbody>
    {% for technology in company_technology %}
        <tr>
            <td><a href="{% url 'company_account:edit_technology' id=technology.id %}">{{ technology.equipment }} </a> </td>
            <td>{{ technology.it }}</td>
            <td>{{ technology.resanddev }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
    </div>

</div>


<div id="right-bar">
        <h2>{% trans 'Enterprenuership' %}</h2>
        <ul>
            <li class="region"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/region-choose" >{% trans 'Region choose' %}</a></li>
            <li class="formation"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/business-formation" >{% trans 'Business Formation' %}</a></li>
            <li class="investments"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/business-investments" >{% trans 'Business Investments' %}</a></li>
            <li class="market"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/market-research" >{% trans 'Market Research' %}</a></li>
            <li class="regional"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/regional-promotion" >{% trans 'Regional Promotion' %}</a></li>
            <li class="partners"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/partners-search" >{% trans 'Partners search' %}</a></li>
            <li class="representative"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/representative-office">{% trans 'Representative Office' %}</a></li>
            <li class="ready"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/ready-businesses" >{% trans 'Ready Businesses' %}</a></li>
        </ul>

</div>
{% endblock %}

templates/company_account/confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block title %} {% trans 'Confirm Account' %} {% endblock %}
{% block content %}

   <h1>{% trans 'Confirm registration' %}</h1>

    <div>
        
        {% if success %}
            <p>{% trans 'successufully registered.' %}
                <a style="text-decoration: none; margin-left: 10px;" href="/{{ LANGUAGE_CODE }}">{% trans 'Sign in' %}</a>
            </p>


        {% elif has_account %}
            <p>{% trans 'You are already registered. Please' %}
                <a style="text-decoration: none; margin-left: 3px;" href="/{{ LANGUAGE_CODE }}">{% trans 'Sign in' %}</a>
            </p>
        {% elif expired %}
            <p>{% trans 'Registering failed. Register again.' %}</p>
         {% endif %}       
    </div>   

	
{% endblock %}

templates/company_account/employee_info.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Employee Information' %} {% endblock %}

{% block content %}
    <h1>{% trans 'Employee Information' %}</h1>
    {% if wrong_user %}
        {% trans 'You have not permission to show this employee information' %}
    {% else %}
        <div class="partner">
            <div class="ui two column middle  relaxed grid basic segment">
                <div style="font-size: 13px; margin-top:0px;" class="column">
                    <div class="label"> {% trans ' Email' %} </div><div > {{ employee.email }} </div>
                    <div class="label"> {% trans 'Name' %} </div><div> {{ employee.get_full_name }} </div>
                    <div class="label"> {% trans 'Position' %} </div><div > {{ employee.position }}</div>
                    <div class="label"> {% trans 'Phone' %} </div><div > {% if employee.phone %} {{ employee.phone }}{% else %}...{% endif %} </div>
                    <div class="label"> {% trans 'Country' %} </div><div > {% if employee.country %} {{ employee.country }}{% else %}...{% endif %} </div>
                    <div class="label"> {% trans 'City' %} </div><div> {% if employee.city %} {{ employee.city }}{% else %}...{% endif %} </div>
                </div>
            </div>
        </div>
    {% endif %}


{% endblock %}

templates/company_account/login.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} {% trans 'Log in Partnership Portal' %} {% endblock %}
}
{% block content %}
    <h1>{% trans 'Log in Partnership Portal' %}</h1>
    <div class="ui two column middle aligned relaxed grid basic segment">
        <div class="column">
            <div class="ui form segment">
                <form action="{% url 'company_account:user_login' %}" method="post">
                    {% csrf_token %}
                    {% if req_url %}
                        <input type="hidden" name="next" value="{{ req_url }}" />
                    {% endif %}

                    <div {% if form.username.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ form.username.label_tag }}
                          <div class="ui left labeled icon input">
                              {{ form.username }}
                              <i class="user icon"></i>
                                  <div class="ui corner label">
                                    <i class="asterisk icon"></i>
                                  </div>
                          </div>
                          {% if form.username.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block; width:295px;">
                                    {{ form.username.errors.0 }}
                                </div>
                          {% endif %}
                    </div>
                    <div {% if form.password.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ form.password.label_tag }}
                          <div class="ui left labeled icon input">
                              {{ form.password }}
                              <i class="lock icon"></i>
                                  <div class="ui corner label">
                                    <i class="asterisk icon"></i>
                                  </div>
                          </div>
                          {% if form.password.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;width:295px;">
                                    {{ form.password.errors.0 }}
                                </div>
                          {% endif %}
                    </div>
                    <button style="margin-top: 8px;" class="ui blue submit button">{% trans 'Sign in' %}</button>
                </form>
            </div>
        </div>
        <div class="ui vertical divider">
            {% trans 'Or' %}
        </div>
        <div class="center aligned column">
            <a href="{% url 'company_account:registration' %}">
                <div class=" green ui labeled icon button">
                    <i class="signup icon"></i>
                    {% trans 'Sign Up  as Partner' %}
                </div>
            </a>

{#        </div>#}
{#        <div class="center aligned column">#}

            <a href="{% url 'company_account:user_registration' %}">
                <br>
                <div class=" green ui labeled icon button">
                    <i class="signup icon"></i>
                    {% trans 'Sign Up as User' %}
                </div>
            </a>
        </div>
    </div>



	
{% endblock %}