business_info/urls.py
from django.conf.urls import patterns, url
from business_info import views
from library.views import LibraryView
# from workspace import views as wp_views


urlpatterns = patterns('',

   # url(r'^/$',views.CompanyView.as_view(),  name='company_view'),
   url(r'^(?P<slug>.*?)/companies/$',views.CompanyView.as_view(),  name='stage_company_view'),
   url(r'^(?P<slug>.*?)/library/$',LibraryView.as_view(),  name='stage_library_view'),

   url(r'^(?P<slug>.*?)/$',views.StageView.as_view(),  name='stage_view'),


    #user actions

)

core/urls.py
from django.conf.urls import patterns, url
from core import views
# from workspace import views as wp_views


urlpatterns = patterns('',

   # url(r'^registration/$',views.partner_register,  name='registration'),
   url(r'^(?P<slug>.*?)/$',views.CompanyView.as_view(),  name='company_view'),



    #user actions

)

eurocatalog/urls.py
from django.conf.urls import patterns, include, url

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from core.views import index,search,HomePageView,use_session
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



admin.autodiscover() 
urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # url(r'^', include('core.urls', namespace='core')),
    url(r'^$',HomePageView.as_view(),  name='index'),
   url(r'^session/$',use_session,  name='use_session'),



    url(r'^search/$', search,  name='search'),
    url(r'^categories/', include('catalog.urls', namespace='catalog')),
    url(r'^company/', include('core.urls', namespace='company')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^publications/', include('publications.urls', namespace='publications')),
    url(r'^enterpreneurship/', include('business_info.urls', namespace='enterpreneurship')),
    url(r'^sites/', include('sites.urls', namespace='sites')),
    url(r'^exhibitions/', include('exhibitions.urls', namespace='exhibitions')),
    url(r'^library/',include('library.urls',namespace='library')),
    url(r'^account/',include('company_account.urls',namespace='company_account')),
)

# ... the rest of your URLconf goes here ...

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

library/urls.py
from django.conf.urls import patterns, url
from library import views
# from workspace import views as wp_views


urlpatterns = patterns('',
    # url(r'^$', views.index,  name='index')
   url(r'^(?P<slug>.*?)/$',views.BookDetailView.as_view(),  name='book_detail'),
    #user actions

)

news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from news import views





urlpatterns = patterns('',
    url(r'^$',
        views.news_list, name='news_archive_index'),

    url(r'^(?P<slug>[-\w]+)/$',
        views.news_detail, name='news_detail'),
)

publications/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from publications import views





urlpatterns = patterns('',
    url(r'^$',views.publications_list, name='publications_archive_index'),
    url(r'^c-(?P<slug>.*?)/$',views.CategoryPublicationsView.as_view(), name='category_publications'),

    url(r'^(?P<slug>[-\w]+)/$',views.publications_detail, name='publication_detail'),
     # url(r'^(?P<slug>.*?)-category/$',views.CategoryPublicationsView.as_view(), name='category_publications'),

)

business_info/models.py
from django.db import models
from django.utils.translation import ugettext as _
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from core.models import Locations,Categories,Company
from publications.models import Publications
from sites.models import Sites

# from django.contrib.contenttypes.generic import GenericRelations

# Create your models here.
#
class Stage(models.Model):
    name = models.CharField(_('Name'),max_length = 255)
    slug = models.SlugField(_('Slug'))
    description = models.CharField(_('Description'),max_length = 255)


    class Meta:
        verbose_name = _('Stage')
        verbose_name_plural = _('Stages')

    def __unicode__(self):
        return self.name


class BusinessInfo(models.Model):

    location = models.ForeignKey(Locations)
    stage = models.ForeignKey(Stage)
    content_link = models.ForeignKey(ContentType,related_name = 'businessinfo_content')
    # content_link =  ContentType.objects.get_for_model(Company,Publications)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_link', 'object_id')

    class Meta:
        verbose_name = _('Business Info')
        verbose_name_plural = _('Business Info')


    # def __unicode__(self):              # __unicode__ on Python 2
    #     return self.stage

    # category = models.ForeignKey(Categories)

business_info/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate, login, logout
from django.contrib import admin
from ckeditor.widgets import CKEditorWidget
from django.forms import ModelForm
from business_info.models import BusinessInfo,Stage



class BusinessInfoForm(forms.ModelForm):
    # body = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = BusinessInfo
        fields = '__all__'


class StageForm(forms.ModelForm):
    description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Stage
        fields = '__all__'

business_info/views.py
from django.shortcuts import render
# Http
from django.http import HttpResponse, Http404,HttpResponseRedirect,HttpRequest
# Template
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from business_info.models import Stage,BusinessInfo
from core.models import Company
from django.http import HttpResponse
from django.views.generic import ListView
from django.utils import translation
from django.db.models import Q
from core.models import Locations
from publications.models import Publications
from sites.models import Sites
from library.models import Library
from django.contrib.contenttypes.models import ContentType
# Create your views here.


class StageView(ListView):
    model = Stage
    template_name = 'business_info/stages.html'
    def get_context_data(self, *args, **kwargs):
        context = super(StageView, self).get_context_data(**kwargs)
        context['slug'] = Stage.objects.all()
        category_obj = Stage.objects.get(slug=self.kwargs['slug'])
        objectss = BusinessInfo.objects.filter(stage = category_obj.id)
        ctype = ContentType.objects.get(model='publications')
        publications = BusinessInfo.objects.filter(Q(content_link = ctype) & Q(stage = category_obj.id))[:4]
        ctype = ContentType.objects.get(model='company')        
        companies = BusinessInfo.objects.filter(Q(content_link = ctype) & Q(stage = category_obj.id))[:4]
        ctype = ContentType.objects.get(model='sites')
        sites  = BusinessInfo.objects.filter(Q(content_link = ctype) & Q(stage = category_obj.id))[:4]
        ctype = ContentType.objects.get(model='library')
        libraries  =BusinessInfo.objects.filter(Q(content_link = ctype) & Q(stage = category_obj.id))[:4]
        sites_list = []
        comp_list = []
        pub_list =[]
        library_list =[]
        a = 1
        for y in publications:
            pub_list.append(y.object_id)
        for y in companies:
            comp_list.append(y.object_id)
        for y in sites:
            sites_list.append(y.object_id)
        for y in libraries:
                    library_list.append(y.object_id)

        publication = Publications.objects.filter(id__in= pub_list)
        company = Company.objects.filter(id__in= comp_list)
        site = Sites.objects.filter(id__in= sites_list)
        library = Library.objects.filter(id__in= library_list)



        # category_ob = Stage.objects.filter(parent_id=category_obj.id)

        cur_language = translation.get_language()
        context['cur_language'] = cur_language
        context['stages'] = category_obj
        context['publications'] = publication
        context['companies'] = company
        context['sites'] = site
        context['libraries'] = library
        context['objects'] = objectss

    # context['vacancy_list']=Vacancy.objects.filter(~Q(slug=self.kwargs['slug']))
        return context

class CompanyView(ListView):
    model = Company
    template_name = 'catalog/last_category.html'

    def get_context_data(self, *args, **kwargs):
        context = super(CompanyView, self).get_context_data(**kwargs)
        context['slug'] = Stage.objects.all()
        category_obj = Stage.objects.get(slug=self.kwargs['slug'])
#         objectss = BusinessInfo.objects.filter(stage = category_obj.id)
        ctype = ContentType.objects.get(model='company')
        companies =BusinessInfo.objects.filter(Q(content_link = ctype) & Q(stage = category_obj.id))

        comp_list =[]

        for y in companies:
            comp_list.append(y.object_id)

        company = Company.objects.filter(id__in= comp_list)
        context['companies'] = company

        return context

templates/business_info/stages.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}  Enterprenuership-{{ stages.name }} {% endblock %}
{% block content %}
    <div id="stage">
        <h1>{{ stages.name }}</h1>
        <p>
            {{ stages.description|safe }}
        </p>
        <div class="stage-content">
            <h3>{% trans 'Publications' %}</h3>
{#        {{ objects }}#}
        {% if  publications %}
            <ul>
                {% for publication in publications %}
                   <li> <a href="{% url 'publications:publication_detail'  slug=publication.slug %}">{{ publication.title }}</a></li>
                {% endfor %}
            </ul>
             <br>   <a class="view" href="">{% trans "view all" %}</a>
        {% else %}
            <p>
                {% trans 'There is no information in this section' %}
            </p>
        {% endif %}

        </div>

        <div class="stage-content">
                <h3>{% trans 'Companies' %}</h3>
        {% if companies %}
            <ul>
                {% for company in companies %}
                    <li><a href="{% url 'company:company_view'  slug=company.slug %}"> {{ company.name }}</a></li>
                {% endfor %}
            </ul>
              </br>  <a class="view" href="{% url 'enterpreneurship:stage_company_view' slug=stages.slug %}">{% trans "view all" %}</a>

        {% else %}
                {% trans 'There is no information in this section' %}
        {% endif %}
        </div>

        <div class="stage-content">
                <h3>{% trans 'Useful links' %}</h3>
        {% if sites %}
            <ul>
                {% for site in sites %}
                        <li><a href="{{ site.link }}" target="_blank"> {{ site.title }}</a></li>
                {% endfor %}
            </ul>
            </br>
                <a class="view" href="">{% trans "view all" %}</a>

        {% else %}
                {% trans 'There is no information in this section' %}

        {% endif %}
        </div>

        <div class="stage-content">
            <h3>{% trans 'Library' %}</h3>
            {% if libraries %}
                <ul>
                    {% for library in libraries %}
                        <li><a href="{% url 'library:book_detail' slug=library.slug %}" target="_blank">{{ library.title }}</a></li>
                    {% endfor %}
                </ul>
                 <br/>   <a class="view" href="{% url 'enterpreneurship:stage_library_view' slug=stages.slug%}" >{% trans "view all" %}</a>
            {% else %}
                {% trans 'There is no information in this section' %}
            {% endif %}

        </div>
    </div>
        <div id="right-bar">
        <h2>{% trans 'Enterprenuership' %}</h2>
        <ul>
            <li class="region"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/region-choose" >{% trans 'Region choose' %}</a></li>
            <li class="formation"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/business-formation" >{% trans 'Business Formation' %}</a></li>
            <li class="investments"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/business-investments" >{% trans 'Business Investments' %}</a></li>
            <li class="market"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/market-research" >{% trans 'Market Research' %}</a></li>
            <li class="regional"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/regional-promotion" >{% trans 'Regional Promotion' %}</a></li>
            <li class="partners"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/partners-search" >{% trans 'Partners search' %}</a></li>
            <li class="representative"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/representative-office">{% trans 'Representative Office' %}</a></li>
            <li class="ready"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/ready-businesses" >{% trans 'Ready Businesses' %}</a></li>
        </ul>

    </div>
{% endblock %}