company_account/urls.py
from django.conf.urls import patterns, url
from company_account import views
# from workspace import views as wp_views


urlpatterns = patterns('',

   url(r'^registration/$',views.partner_register,  name='registration'),
    url(r'^login/$',   views.user_login,  name='user_login'),
    url(r'^profile/update/$',   views.profile_update,  name='profile_update'),
    # url(r'^profile/$',   views.profile_info,  name='profile_info'),
    url(r'^logout/$',   views.user_logout,  name='user_logout'),
    url(r'^password/change/$',   views.userPasswordChange,  name='password_change'),

    url(r'^edit/$',   views.companyChange,  name='edit_company'),

    url(r'^company-profile/edit/$',   views.companyProfileChange,  name='edit_profile'),
    url(r'^company-capacity/edit/$',   views.companyCapacityChange,  name='edit_capacity'),

    url(r'^company-clients/new/$',   views.add_client,  name='add_client'),
    url(r'^company-clients/(?P<id>.*?)/$',   views.companyClientChange,  name='edit_client'),

    url(r'^company-products/new/$',   views.add_product,  name='add_product'),
    url(r'^company-products/(?P<id>.*?)/$',   views.companyProductChange,  name='edit_product'),

    url(r'^company-projects/new/$',   views.add_project,  name='add_project'),
    url(r'^company-projects/(?P<id>.*?)/$',   views.companyProjectChange,  name='edit_project'),

    url(r'^company-partners/new/$',   views.add_partner,  name='add_partner'),
    url(r'^company-partners/(?P<id>.*?)/$',   views.companyPartnerChange,  name='edit_partner'),

    url(r'^company-employees/new/$',   views.add_employee,  name='add_employee'),
    url(r'^company-employees/(?P<id>.*?)/$',   views.companyEmplooyesChange,  name='edit_employee'),

    url(r'^company-partnerships/new/$',   views.add_partnership,  name='add_partnership'),
    url(r'^company-partnerships/(?P<id>.*?)/$',   views.companyPartnershipChange,  name='edit_partnership'),

    url(r'^company-certificates/new/$',   views.add_certificate,  name='add_certificate'),
    url(r'^company-certificates/(?P<id>.*?)/$',   views.companyCertificateChange,  name='edit_certificate'),

    url(r'^company-technologies/new/$',   views.add_technology,  name='add_technology'),
    url(r'^company-technologies/(?P<id>.*?)/$',   views.companyTechnologyChange,  name='edit_technology'),

    url(r'^$', views.company_page,  name='company_page'),






    url(r'^confirm/(?P<activation_key>[-\w]+)/$',   views.user_confirm,  name='user_confirm'),
    #user actions

)

core/urls.py
from django.conf.urls import patterns, url
from core import views
# from workspace import views as wp_views


urlpatterns = patterns('',

   # url(r'^registration/$',views.partner_register,  name='registration'),
   url(r'^(?P<slug>.*?)/$',views.CompanyView.as_view(),  name='company_view'),



    #user actions

)

eurocatalog/urls.py
from django.conf.urls import patterns, include, url

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from core.views import index,search,HomePageView,use_session
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



admin.autodiscover() 
urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # url(r'^', include('core.urls', namespace='core')),
    url(r'^$',HomePageView.as_view(),  name='index'),
   url(r'^session/$',use_session,  name='use_session'),



    url(r'^search/$', search,  name='search'),
    url(r'^categories/', include('catalog.urls', namespace='catalog')),
    url(r'^company/', include('core.urls', namespace='company')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^publications/', include('publications.urls', namespace='publications')),
    url(r'^enterpreneurship/', include('business_info.urls', namespace='enterpreneurship')),
    url(r'^sites/', include('sites.urls', namespace='sites')),
    url(r'^exhibitions/', include('exhibitions.urls', namespace='exhibitions')),
    url(r'^library/',include('library.urls',namespace='library')),
    url(r'^account/',include('company_account.urls',namespace='company_account')),
)

# ... the rest of your URLconf goes here ...

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from news import views





urlpatterns = patterns('',
    url(r'^$',
        views.news_list, name='news_archive_index'),

    url(r'^(?P<slug>[-\w]+)/$',
        views.news_detail, name='news_detail'),
)

catalog/models.py
from django.db import models
from django.utils.translation import ugettext as _

# Create your models here

class Categories(models.Model):
    parent = models.ForeignKey('self',blank=True,null=True)
    title = models.CharField(_('Title'),max_length = 255)
    slug = models.SlugField(_('Slug'),max_length=255)
    page_title = models.CharField(_('Page Title'),max_length = 255)
    icon = models.ImageField(_('Icon'),upload_to = 'catalog/categories',null=True,blank=True)
    description = models.TextField(_('Description'),null=True,blank=True)
    status = models.CharField(_('Status'),max_length = 255)
    meta_description = models.CharField(_('Meta Description'),max_length = 255,null=True,blank=True)
    meta_keyword = models.CharField(_('Meta Keyword'),max_length = 255,null=True,blank=True)
    level = models.PositiveIntegerField(_('Category Level'),null=True,blank=True)
    def __unicode__(self):
        return self.title

    class Meta:
         verbose_name = _('Category')
         verbose_name_plural = _('Categories')

company_account/models.py
from django.db import models

# Create your models here.

news/models.py
try:
    from django.utils.timezone import now as datetime_now
    datetime_now  # workaround for pyflakes
except ImportError:
    from datetime import datetime
    datetime_now = datetime.now

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from core.models import Locations

from . import settings


class PublishedNewsManager(models.Manager):
    """
        Filters out all unpublished and items with a publication date in the future
    """
    def get_query_set(self):
        return super(PublishedNewsManager, self).get_query_set() \
                    .filter(is_published=True) \
                    .filter(pub_date__lte=datetime_now())


class News(models.Model):
    """
    News
    """
    image = models.ImageField('image', upload_to='news')
    title = models.CharField(_('Title'), max_length=255)
    slug = models.SlugField(_('Slug'), unique_for_date='pub_date',
                        help_text=_('A slug is a short name which uniquely identifies the news item for this day'))
    content = models.TextField(_('Content'), blank=True)

    is_published = models.BooleanField(_('Published'), default=False)
    pub_date = models.DateField(_('Publication date'), default=datetime_now)

    created = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(auto_now=True, editable=False)
    location = models.ForeignKey(Locations)

    published = PublishedNewsManager()
    objects = models.Manager()

    link = models.URLField(_('Link'), blank=True, null=True,
        help_text=_('This link will be used a absolute url'
            ' for this item and replaces the view logic. <br />Note that by'
            ' default this only applies for items with an empty "content"'
            ' field.'))

    class Meta:
        verbose_name = _('News')
        verbose_name_plural = _('News')
        ordering = ('-pub_date', )

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        if settings.LINK_AS_ABSOLUTE_URL and self.link:
            if settings.USE_LINK_ON_EMPTY_CONTENT_ONLY and not self.content:
                return self.link
        return reverse('news:news_detail', kwargs={'slug': self.slug})

sites/models.py
from django.db import models
from django.utils.translation import ugettext as _
from core.models import Locations,Categories
from django.core.validators import MaxLengthValidator

# Create your models here.


class Sites(models.Model):
    title = models.CharField(_('Title'),max_length = 255)
    slug = models.SlugField(_('Slug'),help_text=_('A slug is a short name which uniquely identifies the sites item for this day'))

    description = models.TextField(_('Description'),validators=[MaxLengthValidator(500)])
    link = models.URLField(_('Link'))
    location = models.ForeignKey(Locations)
    senddate = models.DateField(_('Send Date'))
    logo = models.ImageField(_('Logo'),upload_to = 'sites')
    active = models.CharField(_('Active'),max_length = 255)
    clicks = models.CharField(_('Clicks'),max_length = 255)
    category = models.ManyToManyField(Categories,'Category')

    class Meta:
        verbose_name = _('Sites')
        verbose_name_plural = _('Sites')


    def __unicode__(self):
        return self.title

core/forms.py
# from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from core.models import Company,CompanyCapacity,CompanyCertificates,CompanyClients,CompanyEmployees,CompanyPartners,Categories,\
    CompanyPartnership,CompanyProducts,CompanyProfile,CompanyProjects,CompanyTechnology,CompanyType,Locations,\
    User,CustomUserManager,UserPasswordRecovery,UserProfile
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django.contrib.auth import authenticate, login, logout
from django.contrib import admin
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.forms import ModelForm
from django.contrib.admin import widgets

from django.forms.extras.widgets import SelectDateWidget
from django.contrib.admin.widgets import AdminDateWidget
from functools import partial
DateInput = partial(forms.DateInput,{'class': 'datepicker'})
#Locations
#
#
#
#                                   Company Object Don't Disturb
#
class CompanyTypeForm(forms.ModelForm):

    class Meta:
        model = CompanyType
        fields = '__all__'

class LocationsForm(forms.ModelForm):
    class Meta:
        model = Locations
        fields = '__all__'


from django.forms.models import inlineformset_factory
# CompanyForm
class CompanyForm(forms.ModelForm):

    description = forms.CharField(widget=CKEditorWidget())
    date = forms.DateField(required=False)
    last_check_date = forms.DateField(required=False)
    class Meta:
        model = Company
        fields = '__all__'
        # fields = ['name','slug','url','description','city','location','address','phone','fax','email','logo','spoken_languages',\
        #           'workingcountries','status','clicks','last_check_date','file_name','comp_type','date','category']
    def __init__(self, *args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget = CKEditorWidget(attrs={'class':'ckeditor','cols': 50, 'rows': 15, 'style': 'resize:none;'})
        # self.fields['date'] = forms.DateTimeField(required=False)
        self.fields['last_check_date']= forms.DateTimeField(required=False)
        self.fields['category'].queryset = Categories.objects.filter(level=3)
        self.fields['category'].helptext = "Use 'Ctrl' for select many categories"
        # self.fields['last_check_date'] = forms.DateField(auto_now_add=True)
        # self.add_fields()
        # self.fields['comp_type'].widget = forms.CheckboxSelectMultiple()
        # comp_type = CompanyType.objects.filter()
        # self.fields['comp_type'].queryset = comp_type
        self.fields["comp_type"].queryset = CompanyType.objects.all()
        # self.fields["comp_type"] = forms.ModelMultipleChoiceField(
           # widget=forms.CheckboxSelectMultiple(),
        # required=False)
        # self.fields["comp_type"].widget = forms.CheckboxSelectMultiple()
        # self.fields["comp_type"].queryset = CompanyType.objects.all()

    #
    # def add_fields(self):
    #     # generate a queryset of the activities to show
    #     # could be sorted if a special order is needed
    #     comptype = CompanyType.objects.all()
    #     if not comptype:
    #         return

        # for a in comptype:
        #     # required false is important to allow the field NOT to be checked
        #     self.fields[a.id] = forms.BooleanField(label=a.name, required=False)

    # CompanyForm = inlineformset_factory(CompanyType, Company)
# CompanyTechnologyForm
class CompanyTechnologyForm(forms.ModelForm):
    equipment = forms.CharField(widget=CKEditorWidget())
    it = forms.CharField(widget=CKEditorWidget())
    resanddev = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = CompanyTechnology
        fields = '__all__'

# CompanyProjectsForm
class CompanyProjectsForm(forms.ModelForm):
    begin_date = forms.DateField(widget=DateInput())
    end_date = forms.DateField(widget=DateInput())

    description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = CompanyProjects
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CompanyProjectsForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget = CKEditorWidget(attrs={'class':'ckeditor','cols': 50, 'rows': 15, 'style': 'resize:none;'})

# CompanyProfileForm
class CompanyProfileForm(forms.ModelForm):

    mission = forms.CharField(widget=CKEditorWidget())
    history = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = CompanyProfile
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CompanyProfileForm, self).__init__(*args, **kwargs)
        self.fields['mission'].widget = CKEditorWidget(attrs={'class':'ckeditor','cols': 50, 'rows': 15, 'style': 'resize:none;'})
        self.fields['history'].widget = CKEditorWidget(attrs={'class':'ckeditor','cols': 50, 'rows': 15, 'style': 'resize:none;'})

# CompanyProductsForm
class CompanyProductsForm(forms.ModelForm):
    date = forms.DateField(widget=DateInput())

    description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = CompanyProducts
        fields =['name','description','photo','link','date']
    def __init__(self, *args, **kwargs):
        super(CompanyProductsForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget = CKEditorWidget(attrs={'class':'ckeditor','cols': 50, 'rows': 15, 'style': 'resize:none;'})

# CompanyPartnership
class CompanyPartnershipForm(forms.ModelForm):

    description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = CompanyPartnership
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CompanyPartnershipForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget = CKEditorWidget(attrs={'class':'ckeditor','cols': 50, 'rows': 15, 'style': 'resize:none;'})



# CompanyPartners
class CompanyPartnersForm(forms.ModelForm):
    since = forms.DateField(widget=DateInput())

    description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = CompanyPartners
        fields =['partner','partnertype','description','since','photo','link']

    def __init__(self, *args, **kwargs):
        super(CompanyPartnersForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget = CKEditorWidget(attrs={'class':'ckeditor','cols': 50, 'rows': 15, 'style': 'resize:none;'})

        # since = forms.DateField(widget=AdminDateWidget())



# CompanyEmployees
class CompanyEmployeesForm(forms.ModelForm):

    about = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = CompanyEmployees
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CompanyEmployeesForm, self).__init__(*args, **kwargs)
        self.fields['about'].widget = CKEditorWidget(attrs={'class':'ckeditor','cols': 50, 'rows': 15, 'style': 'resize:none;'})

# CompanyClients
class CompanyClientsForm(forms.ModelForm):
    since = forms.DateField(widget=DateInput())

    description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = CompanyClients
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CompanyClientsForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget = CKEditorWidget(attrs={'class':'ckeditor','cols': 50, 'rows': 15, 'style': 'resize:none;'})

# CompanyCertificates
class CompanyCertificatesForm(forms.ModelForm):
    receive_year = forms.DateField(widget=DateInput())

    description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = CompanyCertificates
        fields =['name','certification_company','description','receive_year','photo','filename']

    def __init__(self, *args, **kwargs):
        super(CompanyCertificatesForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget = CKEditorWidget(attrs={'class':'ckeditor','cols': 50, 'rows': 15, 'style': 'resize:none;'})

class CompanyCapacityForm(forms.ModelForm):
    # receive_year = forms.DateField(widget=DateInput())
    #
    # description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = CompanyCapacity
        fields =['manufempl','manageempl','volume','production_space']

templates/company_account/edit/edit_company.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
<script type="text/javascript" src="{{ STATIC_URL }}ckeditor/ckeditor/ckeditor.js"></script>

<script>
$(document).ready(function() {
    $('.datepicker').datepicker({ dateFormat: 'yy-mm-dd' });
});
</script>
    <div id="account-company">

<h1>{% trans 'Edit your company' %}</h1>
       <div class="ui form segment">
{#       {{ partnerid }}#}
            <form action="{% url 'company_account:edit_company' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden"  id="id_company"  name="company" value={{ user.company.id }}>
{#                <input type="hidden"  id="id_company"  name="company" value={{ user.company.id }}>#}

                <div class="two fields">
                          <div {% if companyForm.name.errors %} class="field error" {% else %} class="field" {% endif %}>
                            {{ companyForm.name.label_tag }}
                            {{ companyForm.name }}
                            {% if companyForm.name.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                {{ companyForm.name.errors.0 }}
                                </div>
                            {% endif %}
                          </div>
                <div {% if companyForm.url.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.url.label_tag }}
                          {{ companyForm.url }}
                          {% if companyForm.url.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.url.errors.0 }}
                                </div>
                            {% endif %}
                        </div>
                </div>
             <div {% if companyForm.email.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.email.label_tag }}
                          {{ companyForm.email }}
                          {% if companyForm.email.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.email.errors.0 }}
                                </div>
                          {% endif %}
                        </div>

                    <div {% if companyForm.description.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.description.label_tag }}
                          {{ companyForm.description }}
                          {% if companyForm.description.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.description.errors.0 }}
                                </div>
                            {% endif %}
                        </div>
            <div {% if companyForm.location.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.location.label_tag }}
                          {{ companyForm.location }}
                          {% if companyForm.location.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.location.errors.0 }}
                                </div>
                          {% endif %}
                        </div>

            <div class="two fields">
             <div {% if companyForm.city.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.city.label_tag }}
                          {{ companyForm.city }}
                          {% if companyForm.city.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.city.errors.0 }}
                                </div>
                            {% endif %}
                        </div>

                        <div {% if companyForm.address.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.address.label_tag }}
                          {{ companyForm.address }}
                          {% if companyForm.address.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.address.errors.0 }}
                                </div>
                            {% endif %}
                        </div>
            </div>
                <div class="two fields">
                        <div {% if companyForm.logo.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.logo.label_tag }}
                          {{ companyForm.logo }}
                          {% if companyForm.logo.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.logo.errors.0 }}
                                </div>
                            {% endif %}
                        </div>

                      <div {% if companyForm.file_name.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.file_name.label_tag }}
                          {{ companyForm.file_name }}
                          {% if companyForm.file_name.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.file_name.errors.0 }}
                                </div>
                          {% endif %}
                        </div>

             </div>
             <div class="two fields">
                        <div {% if companyForm.phone.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.phone.label_tag }}
                          {{ companyForm.phone }}
                          {% if companyForm.logo.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.phone.errors.0 }}
                                </div>
                            {% endif %}
                        </div>

                      <div {% if companyForm.fax.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.fax.label_tag }}
                          {{ companyForm.fax }}
                          {% if companyForm.fax.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.fax.errors.0 }}
                                </div>
                          {% endif %}
                        </div>
             </div>
            <div class="two fields">
                        <div {% if companyForm.spoken_languages.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.spoken_languages.label_tag }}
                          {{ companyForm.spoken_languages }}
                          {% if companyForm.spoken_languages.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.spoken_languages.errors.0 }}
                                </div>
                            {% endif %}
                        </div>

                      <div {% if companyForm.workingcountries.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.workingcountries.label_tag }}
                          {{ companyForm.workingcountries }}
                          {% if companyForm.workingcountries.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.workingcountries.errors.0 }}
                                </div>
                          {% endif %}
                        </div>
             </div>
              <div class="two fields">
                        <div {% if companyForm.comp_type.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.comp_type.label_tag }}
                          {{ companyForm.comp_type }}
                          {% if companyForm.comp_type.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.comp_type.errors.0 }}
                                </div>
                            {% endif %}
                        </div>

                      <div {% if companyForm.category.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ companyForm.category.label_tag }}
                          {{ companyForm.category }}
                          {% if companyForm.category.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ companyForm.category.errors.0 }}
                                </div>
                          {% endif %}
                        </div>
             </div>

            <input type="hidden"  id="id_slug"  name="slug" value={{ user.company.slug }}>
            <input type="hidden"   id="id_clicks"  name="clicks" value={{ user.company.clicks }}>
            <input type="hidden"  id="id_status"  name="status" value={{ user.company.status }}>
{#            <input type="hidden"  id="id_category"  name="category" value={{ user.company.category }}>#}
{#            <input type="hidden"  id="id_date"  name="date" value={{ user.company.date|date }}>#}
{#            <input type="hidden"  id="id_last_check_date"  name="last_check_date" value={{ user.company.last_check_date|date }}>#}

                         <button class="ui blue button right">{% trans 'Update' %}</button>

            </form>
       </div>

    </div>

{% block right %}
    {% include 'company_account/authorization.html' %}
    {% endblock %}

<div id="right-bar">
        <h2>{% trans 'Enterprenuership' %}</h2>
        <ul>
            <li class="region"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/region-choose" >{% trans 'Region choose' %}</a></li>
            <li class="formation"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/business-formation" >{% trans 'Business Formation' %}</a></li>
            <li class="investments"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/business-investments" >{% trans 'Business Investments' %}</a></li>
            <li class="market"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/market-research" >{% trans 'Market Research' %}</a></li>
            <li class="regional"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/regional-promotion" >{% trans 'Regional Promotion' %}</a></li>
            <li class="partners"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/partners-search" >{% trans 'Partners search' %}</a></li>
            <li class="representative"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/representative-office">{% trans 'Representative Office' %}</a></li>
            <li class="ready"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/ready-businesses" >{% trans 'Ready Businesses' %}</a></li>
        </ul>

</div>
{% endblock %}