catalog/urls.py
from django.conf.urls import patterns, url
from catalog import views
# from workspace import views as wp_views


urlpatterns = patterns('',
    url(r'^dialog/(?P<id>.*?)/$', views.SomeCategoryView.as_view(),name='popup'),
    url(r'^search/$', views.popup,name='popcomp'),
    # url(r'^(?P<category>.*?)/(?P<slugk>.*?)/(?P<slugl>.*?)/(\w+)/$', views.CompanyFilterView.as_view(),  name='filter'),
    # url(r'^(?P<category>.*?)/(?P<slugk>.*?)/(?P<slugl>.*?)/(\w+)/$', views.LastCategoryView.as_view(),  name='lastcategory'),
    url(r'^(?P<category>.*?)/(?P<slugk>.*?)/(?P<slugl>.*?)/$', views.LastCategoryView.as_view(),  name='lastcategory'),

    url(r'^(?P<category>.*?)/(?P<slug>.*?)/$', views.DownCategoryView.as_view(),  name='downcategory'),

    url(r'^(?P<slug>.*?)/$', views.CategoryView.as_view(),  name='category'),
    url(r'^$', views.index,  name='index'),

    #user actions

)

core/urls.py
from django.conf.urls import patterns, url
from core import views
# from workspace import views as wp_views


urlpatterns = patterns('',

   # url(r'^registration/$',views.partner_register,  name='registration'),
   url(r'^(?P<slug>.*?)/$',views.CompanyView.as_view(),  name='company_view'),



    #user actions

)

eurocatalog/urls.py
from django.conf.urls import patterns, include, url

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from core.views import index,search,HomePageView,use_session
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



admin.autodiscover() 
urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # url(r'^', include('core.urls', namespace='core')),
    url(r'^$',HomePageView.as_view(),  name='index'),
   url(r'^session/$',use_session,  name='use_session'),



    url(r'^search/$', search,  name='search'),
    url(r'^categories/', include('catalog.urls', namespace='catalog')),
    url(r'^company/', include('core.urls', namespace='company')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^publications/', include('publications.urls', namespace='publications')),
    url(r'^enterpreneurship/', include('business_info.urls', namespace='enterpreneurship')),
    url(r'^sites/', include('sites.urls', namespace='sites')),
    url(r'^exhibitions/', include('exhibitions.urls', namespace='exhibitions')),
    url(r'^library/',include('library.urls',namespace='library')),
    url(r'^account/',include('company_account.urls',namespace='company_account')),
)

# ... the rest of your URLconf goes here ...

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from news import views





urlpatterns = patterns('',
    url(r'^$',
        views.news_list, name='news_archive_index'),

    url(r'^(?P<slug>[-\w]+)/$',
        views.news_detail, name='news_detail'),
)

catalog/models.py
from django.db import models
from django.utils.translation import ugettext as _

# Create your models here

class Categories(models.Model):
    parent = models.ForeignKey('self',blank=True,null=True)
    title = models.CharField(_('Title'),max_length = 255)
    slug = models.SlugField(_('Slug'),max_length=255)
    page_title = models.CharField(_('Page Title'),max_length = 255)
    icon = models.ImageField(_('Icon'),upload_to = 'catalog/categories',null=True,blank=True)
    description = models.TextField(_('Description'),null=True,blank=True)
    status = models.CharField(_('Status'),max_length = 255)
    meta_description = models.CharField(_('Meta Description'),max_length = 255,null=True,blank=True)
    meta_keyword = models.CharField(_('Meta Keyword'),max_length = 255,null=True,blank=True)
    level = models.PositiveIntegerField(_('Category Level'),null=True,blank=True)
    def __unicode__(self):
        return self.title

    class Meta:
         verbose_name = _('Category')
         verbose_name_plural = _('Categories')

catalog/forms.py
# from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.translation import ugettext_lazy as _

from catalog.models import Categories
from django.contrib.auth import authenticate, login, logout
from django.contrib import admin
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.forms import ModelForm


class CategoriesForm(forms.ModelForm):
    description = forms.CharField(widget=CKEditorWidget())
    icon = forms.ImageField(required =False)
    class Meta:
        model = Categories
        fields = '__all__'

catalog/views.py
from django.shortcuts import render
# Http
from django.http import HttpResponse, Http404,HttpResponseRedirect,HttpRequest
# Template
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from catalog.models import Categories
from core.models import Company
from django.http import HttpResponse
from django.views.generic import ListView
from django.utils import translation
from django.db.models import Q
from core.models import Locations
# Create your views here.

# home page
def index(request):

    categories = Categories.objects.all()
    return render_to_response('catalog/all_categories.html',{'categories':categories},context_instance=RequestContext(request))

class CategoryView(ListView):
    model = Categories
    template_name = 'catalog/parent_category.html'
    def get_context_data(self, *args, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        context['slug'] = Categories.objects.all()
        category_obj = Categories.objects.get(slug=self.kwargs['slug'])

        category_ob = Categories.objects.filter(parent_id=category_obj.id)

        cur_language = translation.get_language()
        context['cur_language'] = cur_language
        context['categories'] = category_ob
        context['title'] = category_obj.title

    # context['vacancy_list']=Vacancy.objects.filter(~Q(slug=self.kwargs['slug']))
        return context

class LastCategoryView(ListView):
    model = Categories
    template_name = 'catalog/last_category.html'
    def get_context_data(self, *args, **kwargs):
        context = super(LastCategoryView, self).get_context_data(**kwargs)
        location = Locations.objects.all()
        # subj_terms = Term.objects.filter(subject = subject_obj.id)
        GLOSSARY_FILTERS = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']

        glossaries = {}
        glossaries1 = {}


        # if subj_terms:
        #     for letter in GLOSSARY_FILTERS:
        #         term_list =[]
        #         for term in subj_terms:
        #             if  term.title.upper().startswith(letter):
        #                 term_list.append(term.title)
        #                 term_list.append(term.description)
        #
        #                 glossaries.update({letter:term_list})
        # glossaries = OrderedDict(sorted(glossaries.items(), key=lambda t: t[0]))
        # url = self.request.build_absolute_uri
        url = self.request.META['QUERY_STRING']


        context['glossary'] =GLOSSARY_FILTERS
        context['slugl'] = Categories.objects.all()
        category_obj = Categories.objects.get(slug=self.kwargs['slugl'])
        upcategory = Categories.objects.get(slug=self.kwargs['category'])
        downcategory = Categories.objects.get(slug=self.kwargs['slugk'])

        # if not self.request.META['HTTP_REFERER']:

        company = Company.objects.filter(category = category_obj.id)

        l = ''
        s = ''
        type = ''
        sorturl = ''
        typeurl = ''
        countryurl = ''
        url = '?type=&country=&sort=&l='
        if '&type' in self.request.META['QUERY_STRING']:
            type = self.request.GET['type']

        # typeurl = Replace(self.request.META['QUERY_STRING'],)
        if "c" in self.request.GET:
            countryurl = self.request.META['QUERY_STRING'].replace('c='+self.request.GET['c'],'')

            c = self.request.GET['c']
            if c == 'all':
                company = company
            else:
                country = Locations.objects.get(code2 = c)
                company = company.filter(location = country.id)

        if "l" in self.request.GET:
            l = self.request.GET['l']
            if l == '0':
                company = company.filter(Q(name__istartswith=l))
            else:
                company = company.filter(name__istartswith=l)

        # typeurl = self.request.META['QUERY_STRING'].replace('type='+self.request.GET['type'],'')

        if "type" in self.request.GET:
            # typeurl = self.request.META['QUERY_STRING'].replace(self.request.META['QUERY_STRING'],'type='+self.request.GET['type'])

            type = self.request.GET['type']
            if type == '0':
                company =company
            else:
                company = company.filter(comp_type = self.request.GET['type'])

        if "s" in self.request.GET:
            sorturl = self.request.META['QUERY_STRING'].replace('&s='+self.request.GET['s'],'')

            s = self.request.GET['s']
            if s == '1':
                company = company.order_by('name')
            if s == '2':
                company = company.order_by('-date')
            if s == '3':
                company = company.order_by('-clicks')


        context['upcategory'] = upcategory
        context['downcategory'] = downcategory
        context['lastcategory'] = category_obj
        context['locations'] = location
        context['url'] = url
        context['typeurl'] = typeurl
        context['countryurl'] = countryurl
        context['sorturl'] = sorturl
        context['l'] = l
        context['type'] = type
        context['s'] = s
        context['companies'] = company
        cur_language = translation.get_language()
        context['cur_language'] = cur_language

    # context['vacancy_list'] = Vacancy.objects.filter(~Q(slug=self.kwargs['slug']))
        return context

class DownCategoryView(ListView):
    model = Categories
    template_name = 'catalog/second_category.html'
    def get_context_data(self, *args, **kwargs):
        context = super(DownCategoryView, self).get_context_data(**kwargs)
        category_obj = Categories.objects.get(slug=self.kwargs['slug'])

        category_ob = Categories.objects.filter(parent_id=category_obj.id)
        context['categories'] = category_ob
        cur_language = translation.get_language()
        context['cur_language'] = cur_language
        context['title'] = category_obj.title
    # context['vacancy_list']=Vacancy.objects.filter(~Q(slug=self.kwargs['slug']))
        return context

        # return self.render_to_response(context)
class CompanyFilterView(ListView):
    model = Company
    template_name = 'catalog/second_category.html'

    def get_context_data(self, *args, **kwargs):
        context = super(CompanyFilterView, self).get_context_data(**kwargs)
        a = LastCategoryView.context_object_name.company.order_by('name')
        context['a'] = a

        return context

# def get_date(request):
#
#     qs = Company.MyModel.objects.all()
#
#     sort = request.session.get('TALENT_SORT', None)
#     if sort in ["alphabetical", "created_date"]:
#         qs = qs.order_by(sort)
#
#     myfilter = request.session.get("TALENT_FILTER", None)
#     if myfilter in ["top_ten","bottom_ten"]:
#         qs = qs.filter( .... )
#     return render_to_response()



class SomeCategoryView(ListView):
    model = Categories
    template_name = 'catalog/popup.html'
    def get_context_data(self, *args, **kwargs):
        # if self.request.is_ajax():
        context = super(SomeCategoryView, self).get_context_data(**kwargs)
        context['id'] = Categories.objects.all()
        cat2 = Categories.objects.get(id=self.kwargs['id'])
        cat1 = Categories.objects.get(id=cat2.parent_id)

        category_obj = Categories.objects.filter(parent_id=self.kwargs['id'])

        # company = Company.objects.filter(category = category_obj.id)
        context['categories'] = category_obj
        context['cat2'] = cat2.slug
        context['cat1'] = cat1.slug


        cur_language = translation.get_language()
        context['cur_language'] = cur_language

    # context['vacancy_list']=Vacancy.objects.filter(~Q(slug=self.kwargs['slug']))
        return context

def popup(request):
    # categories=[]
    company = []

    # if request.method = "POST":
    categories = request.POST.getlist('categories')
    # categories = request.POST["categories"].split("_")

    company = Company.objects.filter(category__in = categories).distinct()
    # company = Company.objects.filter(category__in=categories).distinct(id)

    # categories = Categories.objects.filter(parent_id =id)
    return render_to_response('company/filtir_company.html',{'categories':categories,'company':company},context_instance=RequestContext(request))

templates/catalog/all_categories.html
{% extends 'base.html' %}
{% load i18n %}
<script>

$("#dialog").dialog({
    modal: true,
    autoOpen: false
});
$("a.delete").click(function(e) {
    e.preventDefault();
    var id = $(this).attr('id');
    $("#dialog").dialog('option', 'buttons', {
        "Delete": function() {
            $.post({
                url: {% url myapp.views.delete %},
                data: {'id': id},
                success: function() {
{#                   # whatever you like, some fancy effect that removes the object#}
                }
            });
            $(this).dialog("close");
        },
        "Cancel": function() {
            $(this).dialog("close");
        }
    });
    $("#dialog").dialog("open");
    return false;
});
</script>


{% block content %}



    <script>
    $(document).ready(function () {
{#    $(".ui-dialog-titlebar" ).hide();#}

    $(".test").click(function () {
{#        var myPos = [ $(window).width() / 100 , 50 ];#}

        $("#thedialog").attr('src', $(this).attr("href"));

        $("#somediv").dialog({
{#            dialogClass: 'fixed-dialog',#}
            width: 770,
            height: 450,
            position: ['center', 'top','left'],
            closeOnEscape: true,

            modal: true


        });
{#        .css({#}
{#             "position": "fixed",#}
{#             "top": "50px",#}
{#             "left": "50px"#}
{#        });#}
{#      $(".ui-dialog-titlebar").hide();#}
        return false;
    });

});

    </script>


    <div id="categories">

    {% for category in categories %}
        {% if not category.parent %}

                <div class="category">

            <h3>{{ category.title }}</h3>
                <div class="downcategory">
                 <ul>
                    {% for object in categories %}
{#                                <a href="dialog/32" class="test" >TestCategory</a><br>#}

                        {% if object.parent_id == category.id %}
{#                           <li> {{ object.title }}</li>#}
                            <li>
                                <a href="dialog/{{ object.id }}" class="test" >{{ object.title }}</a><br>

                                <div id="somediv"  style="display:none;">
                                    <iframe id="thedialog" width="500" height="300"></iframe>
                                </div>


                            </li>
                        {% endif %}
                    {% endfor %}
                 </ul>
            </div>

            </div>
        {% endif %}
    {% endfor %}

    </div>


       <div id="right-bar">
        <h2>{% trans 'Enterprenuership' %}</h2>
        <ul>
            <li class="region"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/region-choose" >{% trans 'Region choose' %}</a></li>
            <li class="formation"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/business-formation" >{% trans 'Business Formation' %}</a></li>
            <li class="investments"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/business-investments" >{% trans 'Business Investments' %}</a></li>
            <li class="market"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/market-research" >{% trans 'Market Research' %}</a></li>
            <li class="regional"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/regional-promotion" >{% trans 'Regional Promotion' %}</a></li>
            <li class="partners"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/partners-search" >{% trans 'Partners search' %}</a></li>
            <li class="representative"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/representative-office">{% trans 'Representative Office' %}</a></li>
            <li class="ready"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/ready-businesses" >{% trans 'Ready Businesses' %}</a></li>
        </ul>

    </div>
{% endblock %}

templates/catalog/last_category.html
{% extends 'company/all_company.html' %}
{% load i18n %}
{% load increment_tags %}
{% block title %}   {% trans 'Companies' %}        {% endblock %}

{% block company %}
    <div id="cat-company">
    {% if companies %}

            {% with count=1 %}
        {% for company in companies %}

            {% if count|divisibleby:2 %}
                <div class="companyr">

            {% else %}
                <div class="companyl">

            {% endif %}


            <h3><a  href="{% url 'company:company_view' slug=company.slug %}"> {{ company.name }}</a></h3>
                <div class="image">
                    <img src="{{ MEDIA_URL }}{{ company.logo }}">
                </div>
{#            <a href="/{{ current_language }}/{{ company.slug }}">{{ company.name }}</a>#}
            <div class="comp-detail">
                <ul>
                   <li class="comp_type">
                   {% for cmp in company.comp_type.all %}
                   {{ cmp.name }}, 
                   {% endfor %}
                   </li>
                   <li class="location"> {{ company.location_id }}</li>
                   <li class="www"> <a target="_blank" href="{{ company.url }}">{{ company.url }}</a></li>
                </ul>
            </div>
{#            <div class="text">#}
               <p>{{ company.description|striptags|safe |truncatewords:30 }} <a href="{% url 'company:company_view' slug=company.slug %}"> {% trans 'read more' %} </a></p>

{#            </div>#}

                 {% increment count %}
        </div>
        {% endfor %}
     	{% endwith %}
{% else %}
        <h3>
        {% trans 'There is no any company in this category' %}
        </h3>
    {% endif %}

        </div>

{% endblock %}

templates/catalog/parent_category.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <div id="categories">
    <h1>{{title}}</h1>
    <ul>
    {% for category in categories %}
        <li>
        <a href="{{ category.slug }}">{{ category.title }}</a>
        </li>
    {% endfor %}
    </ul>
    </div>

    {% block right %}
    {% include 'company_account/authorization.html' %}
    {% endblock %}
        <div id="right-bar">

        <h2>{% trans 'Enterprenuership' %}</h2>
        <ul>
            <li class="region"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/region-choose" >{% trans 'Region choose' %}</a></li>
            <li class="formation"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/business-formation" >{% trans 'Business Formation' %}</a></li>
            <li class="investments"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/business-investments" >{% trans 'Business Investments' %}</a></li>
            <li class="market"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/market-research" >{% trans 'Market Research' %}</a></li>
            <li class="regional"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/regional-promotion" >{% trans 'Regional Promotion' %}</a></li>
            <li class="partners"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/partners-search" >{% trans 'Partners search' %}</a></li>
            <li class="representative"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/representative-office">{% trans 'Representative Office' %}</a></li>
            <li class="ready"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/ready-businesses" >{% trans 'Ready Businesses' %}</a></li>
        </ul>

    </div>
{% endblock %}

templates/catalog/popup.html
{% load i18n %}
<head>
       <link  type="text/css" rel="stylesheet" media="all" href="{{ STATIC_URL }}css/style.css" />

</head>
<title>{% trans 'Select one or more categories' %}</title>
<div id="popup">
<h2>{% trans 'Select category' %}</h2>
{#<form  target="_parent" action="{% url 'catalog:popcomp' %}" METHOD="POST">#}
{#{% csrf_token %}#}
{% for object in categories %}
    <li>
{#    <input type="checkbox" name="categories" value="{{ object.id }}">#}
    <a target="_parent" href="{% url 'catalog:lastcategory' category=cat1 slugk=cat2 slugl=object.slug %}">{{ object.title }}</a>
    </li>
{% endfor %}

{#            <button  class="button" >{% trans 'Search' %} </button>#}

{#</form>#}
{#<li><input type="checkbox"><a target="_parent" href="/en/categories/construction-design/architects-town-planning-town-planners/">sddasdasdasads</a></li>#}
{#<li><input type="checkbox">sddasdasdasads</li>#}



</div>

templates/catalog/second_category.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}   {% trans 'Companies' %}        {% endblock %}

{% block content %}
    <div id="cat-center">
    <h1>{{title}}</h1>
    <ul>
        {% for category in categories %}
            <li><a href="{{ category.slug }}">{{ category.title }}</a></li>
        {% endfor %}
    </ul>
    </div>

{% block right %}
    {% include 'company_account/authorization.html' %}
    {% endblock %}
    <div id="right-bar">
        <h2>{% trans 'Enterprenuership' %}</h2>
        <ul>
            <li class="region"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/region-choose" >{% trans 'Region choose' %}</a></li>
            <li class="formation"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/business-formation" >{% trans 'Business Formation' %}</a></li>
            <li class="investments"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/business-investments" >{% trans 'Business Investments' %}</a></li>
            <li class="market"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/market-research" >{% trans 'Market Research' %}</a></li>
            <li class="regional"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/regional-promotion" >{% trans 'Regional Promotion' %}</a></li>
            <li class="partners"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/partners-search" >{% trans 'Partners search' %}</a></li>
            <li class="representative"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/representative-office">{% trans 'Representative Office' %}</a></li>
            <li class="ready"><a href="/{{ LANGUAGE_CODE }}/enterpreneurship/ready-businesses" >{% trans 'Ready Businesses' %}</a></li>
        </ul>

    </div>

{% endblock %}